<?php

namespace Modules\Agency\Database\Seeders;

use Illuminate\Database\Seeder;

class AgencyUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->whereBetween('id', [41537, 41636])->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 41537,
                'name' => 'bambang-irawan',
                'email' => 'bambang-irawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            1 => 
            array (
                'id' => 41538,
                'name' => 'ratna-puspita',
                'email' => 'ratna-puspita@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            2 => 
            array (
                'id' => 41539,
                'name' => 'hendra-wijaya',
                'email' => 'hendra-wijaya@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            3 => 
            array (
                'id' => 41540,
                'name' => 'yulianti-rahayu',
                'email' => 'yulianti-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            4 => 
            array (
                'id' => 41541,
                'name' => 'agus-supriyadi',
                'email' => 'agus-supriyadi@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            5 => 
            array (
                'id' => 41542,
                'name' => 'dian-lestari',
                'email' => 'dian-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            6 => 
            array (
                'id' => 41543,
                'name' => 'fajar-nugroho',
                'email' => 'fajar-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            7 => 
            array (
                'id' => 41544,
                'name' => 'eko-prasetyo',
                'email' => 'eko-prasetyo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            8 => 
            array (
                'id' => 41545,
                'name' => 'sari-dewanti',
                'email' => 'sari-dewanti@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            9 => 
            array (
                'id' => 41546,
                'name' => 'rina-anggraini',
                'email' => 'rina-anggraini@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:14:39',
                'updated_at' => '2026-09-08 04:14:39',
            ),
            10 => 
            array (
                'id' => 41547,
                'name' => 'ahmad-zaini',
                'email' => 'ahmad-zaini@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            11 => 
            array (
                'id' => 41548,
                'name' => 'sri-rahayu',
                'email' => 'sri-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            12 => 
            array (
                'id' => 41549,
                'name' => 'dedi-kurniawan',
                'email' => 'dedi-kurniawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            13 => 
            array (
                'id' => 41550,
                'name' => 'lina-marlina',
                'email' => 'lina-marlina@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            14 => 
            array (
                'id' => 41551,
                'name' => 'rudi-santoso',
                'email' => 'rudi-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            15 => 
            array (
                'id' => 41552,
                'name' => 'dewi-sartika',
                'email' => 'dewi-sartika@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            16 => 
            array (
                'id' => 41553,
                'name' => 'bambang-hermanto',
                'email' => 'bambang-hermanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            17 => 
            array (
                'id' => 41554,
                'name' => 'yuni-astuti',
                'email' => 'yuni-astuti@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            18 => 
            array (
                'id' => 41555,
                'name' => 'joko-widodo',
                'email' => 'joko-widodo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            19 => 
            array (
                'id' => 41556,
                'name' => 'eva-susanti',
                'email' => 'eva-susanti@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            20 => 
            array (
                'id' => 41557,
                'name' => 'herman-syah',
                'email' => 'herman-syah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            21 => 
            array (
                'id' => 41558,
                'name' => 'nurhayati',
                'email' => 'nurhayati@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            22 => 
            array (
                'id' => 41559,
                'name' => 'teguh-santoso',
                'email' => 'teguh-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            23 => 
            array (
                'id' => 41560,
                'name' => 'rina-puspitasari',
                'email' => 'rina-puspitasari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            24 => 
            array (
                'id' => 41561,
                'name' => 'adi-nugroho',
                'email' => 'adi-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            25 => 
            array (
                'id' => 41562,
                'name' => 'siti-nurjanah',
                'email' => 'siti-nurjanah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            26 => 
            array (
                'id' => 41563,
                'name' => 'wahyu-hidayat',
                'email' => 'wahyu-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            27 => 
            array (
                'id' => 41564,
                'name' => 'endang-sri',
                'email' => 'endang-sri@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            28 => 
            array (
                'id' => 41565,
                'name' => 'fauzi-rahman',
                'email' => 'fauzi-rahman@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            29 => 
            array (
                'id' => 41566,
                'name' => 'mega-wati',
                'email' => 'mega-wati@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            30 => 
            array (
                'id' => 41567,
                'name' => 'slamet-riyadi',
                'email' => 'slamet-riyadi@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            31 => 
            array (
                'id' => 41568,
                'name' => 'kartika-sari',
                'email' => 'kartika-sari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            32 => 
            array (
                'id' => 41569,
                'name' => 'yusuf-maulana',
                'email' => 'yusuf-maulana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            33 => 
            array (
                'id' => 41570,
                'name' => 'indah-permata',
                'email' => 'indah-permata@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            34 => 
            array (
                'id' => 41571,
                'name' => 'rizki-ramadhan',
                'email' => 'rizki-ramadhan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            35 => 
            array (
                'id' => 41572,
                'name' => 'ayu-lestari',
                'email' => 'ayu-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            36 => 
            array (
                'id' => 41573,
                'name' => 'budi-hartono',
                'email' => 'budi-hartono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            37 => 
            array (
                'id' => 41574,
                'name' => 'ratna-dewi',
                'email' => 'ratna-dewi@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            38 => 
            array (
                'id' => 41575,
                'name' => 'agung-laksono',
                'email' => 'agung-laksono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            39 => 
            array (
                'id' => 41576,
                'name' => 'dian-sastro',
                'email' => 'dian-sastro@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 04:21:28',
                'updated_at' => '2026-09-08 04:21:28',
            ),
            40 => 
            array (
                'id' => 41577,
                'name' => 'vina-yuliana',
                'email' => 'vina-yuliana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            41 => 
            array (
                'id' => 41578,
                'name' => 'yuli-handayani',
                'email' => 'yuli-handayani@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            42 => 
            array (
                'id' => 41579,
                'name' => 'candra-yuliana',
                'email' => 'candra-yuliana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            43 => 
            array (
                'id' => 41580,
                'name' => 'zainal-ginting',
                'email' => 'zainal-ginting@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            44 => 
            array (
                'id' => 41581,
                'name' => 'andi-susanto',
                'email' => 'andi-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            45 => 
            array (
                'id' => 41582,
                'name' => 'hesti-siregar',
                'email' => 'hesti-siregar@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            46 => 
            array (
                'id' => 41583,
                'name' => 'dedi-wibowo',
                'email' => 'dedi-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            47 => 
            array (
                'id' => 41584,
                'name' => 'oscar-saputra',
                'email' => 'oscar-saputra@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            48 => 
            array (
                'id' => 41585,
                'name' => 'bella-firmansyah',
                'email' => 'bella-firmansyah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            49 => 
            array (
                'id' => 41586,
                'name' => 'oscar-kusuma',
                'email' => 'oscar-kusuma@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            50 => 
            array (
                'id' => 41587,
                'name' => 'hendra-susanto',
                'email' => 'hendra-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            51 => 
            array (
                'id' => 41588,
                'name' => 'yanti-nasution',
                'email' => 'yanti-nasution@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            52 => 
            array (
                'id' => 41589,
                'name' => 'maya-hartono',
                'email' => 'maya-hartono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            53 => 
            array (
                'id' => 41590,
                'name' => 'ayu-ramadhani',
                'email' => 'ayu-ramadhani@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            54 => 
            array (
                'id' => 41591,
                'name' => 'putri-wulandari',
                'email' => 'putri-wulandari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            55 => 
            array (
                'id' => 41592,
                'name' => 'yanti-santoso',
                'email' => 'yanti-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            56 => 
            array (
                'id' => 41593,
                'name' => 'budi-lubis',
                'email' => 'budi-lubis@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            57 => 
            array (
                'id' => 41594,
                'name' => 'candra-yuliana2',
                'email' => 'candra-yuliana2@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            58 => 
            array (
                'id' => 41595,
                'name' => 'qori-lestari',
                'email' => 'qori-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            59 => 
            array (
                'id' => 41596,
                'name' => 'hesti-dalimunthe',
                'email' => 'hesti-dalimunthe@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            60 => 
            array (
                'id' => 41597,
                'name' => 'fitri-sinaga',
                'email' => 'fitri-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            61 => 
            array (
                'id' => 41598,
                'name' => 'oki-lestari',
                'email' => 'oki-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            62 => 
            array (
                'id' => 41599,
                'name' => 'tono-yuliana',
                'email' => 'tono-yuliana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            63 => 
            array (
                'id' => 41600,
                'name' => 'fitri-purba',
                'email' => 'fitri-purba@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            64 => 
            array (
                'id' => 41601,
                'name' => 'budi-saragih',
                'email' => 'budi-saragih@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            65 => 
            array (
                'id' => 41602,
                'name' => 'maya-hartono2',
                'email' => 'maya-hartono2@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            66 => 
            array (
                'id' => 41603,
                'name' => 'krisna-melati',
                'email' => 'krisna-melati@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            67 => 
            array (
                'id' => 41604,
                'name' => 'fitri-firmansyah',
                'email' => 'fitri-firmansyah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            68 => 
            array (
                'id' => 41605,
                'name' => 'citra-ramadhani',
                'email' => 'citra-ramadhani@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            69 => 
            array (
                'id' => 41606,
                'name' => 'dewi-kurniawan',
                'email' => 'dewi-kurniawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            70 => 
            array (
                'id' => 41607,
                'name' => 'umar-santoso',
                'email' => 'umar-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            71 => 
            array (
                'id' => 41608,
                'name' => 'gita-hartono',
                'email' => 'gita-hartono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            72 => 
            array (
                'id' => 41609,
                'name' => 'oki-ramadhani',
                'email' => 'oki-ramadhani@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            73 => 
            array (
                'id' => 41610,
                'name' => 'sari-nasution',
                'email' => 'sari-nasution@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            74 => 
            array (
                'id' => 41611,
                'name' => 'hendra-saragih',
                'email' => 'hendra-saragih@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            75 => 
            array (
                'id' => 41612,
                'name' => 'kartika-hartono',
                'email' => 'kartika-hartono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            76 => 
            array (
                'id' => 41613,
                'name' => 'putri-wibowo',
                'email' => 'putri-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            77 => 
            array (
                'id' => 41614,
                'name' => 'citra-situmorang',
                'email' => 'citra-situmorang@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            78 => 
            array (
                'id' => 41615,
                'name' => 'lukman-manullang',
                'email' => 'lukman-manullang@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            79 => 
            array (
                'id' => 41616,
                'name' => 'kartika-panjaitan',
                'email' => 'kartika-panjaitan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            80 => 
            array (
                'id' => 41617,
                'name' => 'rahmat-panjaitan',
                'email' => 'rahmat-panjaitan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            81 => 
            array (
                'id' => 41618,
                'name' => 'budi-rahayu2',
                'email' => 'budi-rahayu2@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            82 => 
            array (
                'id' => 41619,
                'name' => 'citra-pratama',
                'email' => 'citra-pratama@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            83 => 
            array (
                'id' => 41620,
                'name' => 'lina-sari',
                'email' => 'lina-sari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            84 => 
            array (
                'id' => 41621,
                'name' => 'wahyu-saputra',
                'email' => 'wahyu-saputra@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            85 => 
            array (
                'id' => 41622,
                'name' => 'eka-tambunan',
                'email' => 'eka-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            86 => 
            array (
                'id' => 41623,
                'name' => 'candra-hutapea',
                'email' => 'candra-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            87 => 
            array (
                'id' => 41624,
                'name' => 'dedi-hartono',
                'email' => 'dedi-hartono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            88 => 
            array (
                'id' => 41625,
                'name' => 'umar-pratama',
                'email' => 'umar-pratama@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            89 => 
            array (
                'id' => 41626,
                'name' => 'oki-sihombing',
                'email' => 'oki-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            90 => 
            array (
                'id' => 41627,
                'name' => 'eka-setiawan',
                'email' => 'eka-setiawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            91 => 
            array (
                'id' => 41628,
                'name' => 'dedi-saragih',
                'email' => 'dedi-saragih@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            92 => 
            array (
                'id' => 41629,
                'name' => 'sari-simarmata',
                'email' => 'sari-simarmata@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            93 => 
            array (
                'id' => 41630,
                'name' => 'gunawan-nainggolan',
                'email' => 'gunawan-nainggolan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            94 => 
            array (
                'id' => 41631,
                'name' => 'vivi-zahara',
                'email' => 'vivi-zahara@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            95 => 
            array (
                'id' => 41632,
                'name' => 'qori-sinaga',
                'email' => 'qori-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            96 => 
            array (
                'id' => 41633,
                'name' => 'citra-wibowo',
                'email' => 'citra-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            97 => 
            array (
                'id' => 41634,
                'name' => 'julia-sari',
                'email' => 'julia-sari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            98 => 
            array (
                'id' => 41635,
                'name' => 'andi-sihombing',
                'email' => 'andi-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            99 => 
            array (
                'id' => 41636,
                'name' => 'dedi-susanto',
                'email' => 'dedi-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
        ));
        
        
    }
}