<?php

namespace Modules\Agency\Database\Seeders;

use Illuminate\Database\Seeder;

class AgencyStaffsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('agency_staffs')->delete();
        
        \DB::table('agency_staffs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 41537,
                'agency_id' => 10101,
                'unit_id' => NULL,
                'realname' => 'Bambang Irawan',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 41538,
                'agency_id' => 10102,
                'unit_id' => NULL,
                'realname' => 'Ratna Puspita',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 41539,
                'agency_id' => 10103,
                'unit_id' => NULL,
                'realname' => 'Hendra Wijaya',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 41540,
                'agency_id' => 10104,
                'unit_id' => NULL,
                'realname' => 'Yulianti Rahayu',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 41541,
                'agency_id' => 10105,
                'unit_id' => NULL,
                'realname' => 'Agus Supriyadi',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 41542,
                'agency_id' => 10106,
                'unit_id' => NULL,
                'realname' => 'Dian Lestari',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 41543,
                'agency_id' => 10107,
                'unit_id' => NULL,
                'realname' => 'Fajar Nugroho',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 41544,
                'agency_id' => 10108,
                'unit_id' => NULL,
                'realname' => 'Eko Prasetyo',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 41545,
                'agency_id' => 10109,
                'unit_id' => NULL,
                'realname' => 'Sari Dewanti',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 41546,
                'agency_id' => 10110,
                'unit_id' => NULL,
                'realname' => 'Rina Anggraini',
                'nip' => NULL,
                'jabatan' => 'Admin Dinas',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 41547,
                'agency_id' => 10101,
                'unit_id' => 10111,
                'realname' => 'Ahmad Zaini',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 41548,
                'agency_id' => 10101,
                'unit_id' => 10112,
                'realname' => 'Sri Rahayu',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 41549,
                'agency_id' => 10101,
                'unit_id' => 10113,
                'realname' => 'Dedi Kurniawan',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 41550,
                'agency_id' => 10102,
                'unit_id' => 10114,
                'realname' => 'Lina Marlina',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 41551,
                'agency_id' => 10102,
                'unit_id' => 10115,
                'realname' => 'Rudi Santoso',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 41552,
                'agency_id' => 10102,
                'unit_id' => 10116,
                'realname' => 'Dewi Sartika',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 41553,
                'agency_id' => 10103,
                'unit_id' => 10117,
                'realname' => 'Bambang Hermanto',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 41554,
                'agency_id' => 10103,
                'unit_id' => 10118,
                'realname' => 'Yuni Astuti',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 41555,
                'agency_id' => 10103,
                'unit_id' => 10119,
                'realname' => 'Joko Widodo',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 41556,
                'agency_id' => 10104,
                'unit_id' => 10120,
                'realname' => 'Eva Susanti',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 41557,
                'agency_id' => 10104,
                'unit_id' => 10121,
                'realname' => 'Herman Syah',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 41558,
                'agency_id' => 10104,
                'unit_id' => 10122,
                'realname' => 'Nurhayati',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 41559,
                'agency_id' => 10105,
                'unit_id' => 10123,
                'realname' => 'Teguh Santoso',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 41560,
                'agency_id' => 10105,
                'unit_id' => 10124,
                'realname' => 'Rina Puspitasari',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 41561,
                'agency_id' => 10105,
                'unit_id' => 10125,
                'realname' => 'Adi Nugroho',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 41562,
                'agency_id' => 10106,
                'unit_id' => 10126,
                'realname' => 'Siti Nurjanah',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 41563,
                'agency_id' => 10106,
                'unit_id' => 10127,
                'realname' => 'Wahyu Hidayat',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 41564,
                'agency_id' => 10106,
                'unit_id' => 10128,
                'realname' => 'Endang Sri',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 41565,
                'agency_id' => 10107,
                'unit_id' => 10129,
                'realname' => 'Fauzi Rahman',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 41566,
                'agency_id' => 10107,
                'unit_id' => 10130,
                'realname' => 'Mega Wati',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 41567,
                'agency_id' => 10107,
                'unit_id' => 10131,
                'realname' => 'Slamet Riyadi',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 41568,
                'agency_id' => 10108,
                'unit_id' => 10132,
                'realname' => 'Kartika Sari',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 41569,
                'agency_id' => 10108,
                'unit_id' => 10133,
                'realname' => 'Yusuf Maulana',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 41570,
                'agency_id' => 10108,
                'unit_id' => 10134,
                'realname' => 'Indah Permata',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 41571,
                'agency_id' => 10109,
                'unit_id' => 10135,
                'realname' => 'Rizki Ramadhan',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 41572,
                'agency_id' => 10109,
                'unit_id' => 10136,
                'realname' => 'Ayu Lestari',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 41573,
                'agency_id' => 10109,
                'unit_id' => 10137,
                'realname' => 'Budi Hartono',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 41574,
                'agency_id' => 10110,
                'unit_id' => 10138,
                'realname' => 'Ratna Dewi',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 41575,
                'agency_id' => 10110,
                'unit_id' => 10139,
                'realname' => 'Agung Laksono',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 41576,
                'agency_id' => 10110,
                'unit_id' => 10140,
                'realname' => 'Dian Sastro',
                'nip' => NULL,
                'jabatan' => 'Admin Unit',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 04:30:33',
                'updated_at' => '2026-09-08 04:30:33',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 41577,
                'agency_id' => 10101,
                'unit_id' => 10111,
                'realname' => 'Vina Yuliana',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 41578,
                'agency_id' => 10101,
                'unit_id' => 10111,
                'realname' => 'Yuli Handayani',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 41579,
                'agency_id' => 10101,
                'unit_id' => 10112,
                'realname' => 'Candra Yuliana',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 41580,
                'agency_id' => 10101,
                'unit_id' => 10112,
                'realname' => 'Zainal Ginting',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 41581,
                'agency_id' => 10101,
                'unit_id' => 10113,
                'realname' => 'Andi Susanto',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 41582,
                'agency_id' => 10101,
                'unit_id' => 10113,
                'realname' => 'Hesti Siregar',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 41583,
                'agency_id' => 10102,
                'unit_id' => 10114,
                'realname' => 'Dedi Wibowo',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 41584,
                'agency_id' => 10102,
                'unit_id' => 10114,
                'realname' => 'Oscar Saputra',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 41585,
                'agency_id' => 10102,
                'unit_id' => 10115,
                'realname' => 'Bella Firmansyah',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 41586,
                'agency_id' => 10102,
                'unit_id' => 10115,
                'realname' => 'Oscar Kusuma',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 41587,
                'agency_id' => 10102,
                'unit_id' => 10116,
                'realname' => 'Hendra Susanto',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 41588,
                'agency_id' => 10102,
                'unit_id' => 10116,
                'realname' => 'Yanti Nasution',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 41589,
                'agency_id' => 10103,
                'unit_id' => 10117,
                'realname' => 'Maya Hartono',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 41590,
                'agency_id' => 10103,
                'unit_id' => 10117,
                'realname' => 'Ayu Ramadhani',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 41591,
                'agency_id' => 10103,
                'unit_id' => 10118,
                'realname' => 'Putri Wulandari',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 41592,
                'agency_id' => 10103,
                'unit_id' => 10118,
                'realname' => 'Yanti Santoso',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 41593,
                'agency_id' => 10103,
                'unit_id' => 10119,
                'realname' => 'Budi Lubis',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 41594,
                'agency_id' => 10103,
                'unit_id' => 10119,
                'realname' => 'Candra Yuliana',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 41595,
                'agency_id' => 10104,
                'unit_id' => 10120,
                'realname' => 'Qori Lestari',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 41596,
                'agency_id' => 10104,
                'unit_id' => 10120,
                'realname' => 'Hesti Dalimunthe',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 41597,
                'agency_id' => 10104,
                'unit_id' => 10121,
                'realname' => 'Fitri Sinaga',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 41598,
                'agency_id' => 10104,
                'unit_id' => 10121,
                'realname' => 'Oki Lestari',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 41599,
                'agency_id' => 10104,
                'unit_id' => 10122,
                'realname' => 'Tono Yuliana',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 41600,
                'agency_id' => 10104,
                'unit_id' => 10122,
                'realname' => 'Fitri Purba',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 41601,
                'agency_id' => 10105,
                'unit_id' => 10123,
                'realname' => 'Budi Saragih',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 41602,
                'agency_id' => 10105,
                'unit_id' => 10123,
                'realname' => 'Maya Hartono',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 41603,
                'agency_id' => 10105,
                'unit_id' => 10124,
                'realname' => 'Krisna Melati',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 41604,
                'agency_id' => 10105,
                'unit_id' => 10124,
                'realname' => 'Fitri Firmansyah',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 41605,
                'agency_id' => 10105,
                'unit_id' => 10125,
                'realname' => 'Citra Ramadhani',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 41606,
                'agency_id' => 10105,
                'unit_id' => 10125,
                'realname' => 'Dewi Kurniawan',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 41607,
                'agency_id' => 10106,
                'unit_id' => 10126,
                'realname' => 'Umar Santoso',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 41608,
                'agency_id' => 10106,
                'unit_id' => 10126,
                'realname' => 'Gita Hartono',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            72 => 
            array (
                'id' => 73,
                'user_id' => 41609,
                'agency_id' => 10106,
                'unit_id' => 10127,
                'realname' => 'Oki Ramadhani',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            73 => 
            array (
                'id' => 74,
                'user_id' => 41610,
                'agency_id' => 10106,
                'unit_id' => 10127,
                'realname' => 'Sari Nasution',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            74 => 
            array (
                'id' => 75,
                'user_id' => 41611,
                'agency_id' => 10106,
                'unit_id' => 10128,
                'realname' => 'Hendra Saragih',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            75 => 
            array (
                'id' => 76,
                'user_id' => 41612,
                'agency_id' => 10106,
                'unit_id' => 10128,
                'realname' => 'Kartika Hartono',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            76 => 
            array (
                'id' => 77,
                'user_id' => 41613,
                'agency_id' => 10107,
                'unit_id' => 10129,
                'realname' => 'Putri Wibowo',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            77 => 
            array (
                'id' => 78,
                'user_id' => 41614,
                'agency_id' => 10107,
                'unit_id' => 10129,
                'realname' => 'Citra Situmorang',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            78 => 
            array (
                'id' => 79,
                'user_id' => 41615,
                'agency_id' => 10107,
                'unit_id' => 10130,
                'realname' => 'Lukman Manullang',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            79 => 
            array (
                'id' => 80,
                'user_id' => 41616,
                'agency_id' => 10107,
                'unit_id' => 10130,
                'realname' => 'Kartika Panjaitan',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            80 => 
            array (
                'id' => 81,
                'user_id' => 41617,
                'agency_id' => 10107,
                'unit_id' => 10131,
                'realname' => 'Rahmat Panjaitan',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            81 => 
            array (
                'id' => 82,
                'user_id' => 41618,
                'agency_id' => 10107,
                'unit_id' => 10131,
                'realname' => 'Budi Rahayu',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            82 => 
            array (
                'id' => 83,
                'user_id' => 41619,
                'agency_id' => 10108,
                'unit_id' => 10132,
                'realname' => 'Citra Pratama',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            83 => 
            array (
                'id' => 84,
                'user_id' => 41620,
                'agency_id' => 10108,
                'unit_id' => 10132,
                'realname' => 'Lina Sari',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            84 => 
            array (
                'id' => 85,
                'user_id' => 41621,
                'agency_id' => 10108,
                'unit_id' => 10133,
                'realname' => 'Wahyu Saputra',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            85 => 
            array (
                'id' => 86,
                'user_id' => 41622,
                'agency_id' => 10108,
                'unit_id' => 10133,
                'realname' => 'Eka Tambunan',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            86 => 
            array (
                'id' => 87,
                'user_id' => 41623,
                'agency_id' => 10108,
                'unit_id' => 10134,
                'realname' => 'Candra Hutapea',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            87 => 
            array (
                'id' => 88,
                'user_id' => 41624,
                'agency_id' => 10108,
                'unit_id' => 10134,
                'realname' => 'Dedi Hartono',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            88 => 
            array (
                'id' => 89,
                'user_id' => 41625,
                'agency_id' => 10109,
                'unit_id' => 10135,
                'realname' => 'Umar Pratama',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            89 => 
            array (
                'id' => 90,
                'user_id' => 41626,
                'agency_id' => 10109,
                'unit_id' => 10135,
                'realname' => 'Oki Sihombing',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            90 => 
            array (
                'id' => 91,
                'user_id' => 41627,
                'agency_id' => 10109,
                'unit_id' => 10136,
                'realname' => 'Eka Setiawan',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            91 => 
            array (
                'id' => 92,
                'user_id' => 41628,
                'agency_id' => 10109,
                'unit_id' => 10136,
                'realname' => 'Dedi Saragih',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            92 => 
            array (
                'id' => 93,
                'user_id' => 41629,
                'agency_id' => 10109,
                'unit_id' => 10137,
                'realname' => 'Sari Simarmata',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            93 => 
            array (
                'id' => 94,
                'user_id' => 41630,
                'agency_id' => 10109,
                'unit_id' => 10137,
                'realname' => 'Gunawan Nainggolan',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            94 => 
            array (
                'id' => 95,
                'user_id' => 41631,
                'agency_id' => 10110,
                'unit_id' => 10138,
                'realname' => 'Vivi Zahara',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            95 => 
            array (
                'id' => 96,
                'user_id' => 41632,
                'agency_id' => 10110,
                'unit_id' => 10138,
                'realname' => 'Qori Sinaga',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            96 => 
            array (
                'id' => 97,
                'user_id' => 41633,
                'agency_id' => 10110,
                'unit_id' => 10139,
                'realname' => 'Citra Wibowo',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            97 => 
            array (
                'id' => 98,
                'user_id' => 41634,
                'agency_id' => 10110,
                'unit_id' => 10139,
                'realname' => 'Julia Sari',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            98 => 
            array (
                'id' => 99,
                'user_id' => 41635,
                'agency_id' => 10110,
                'unit_id' => 10140,
                'realname' => 'Andi Sihombing',
                'nip' => NULL,
                'jabatan' => 'Pengawas Ketenagakerjaan',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
            99 => 
            array (
                'id' => 100,
                'user_id' => 41636,
                'agency_id' => 10110,
                'unit_id' => 10140,
                'realname' => 'Dedi Susanto',
                'nip' => NULL,
                'jabatan' => 'Pengawas Spesialis',
                'phone' => NULL,
                'is_active' => 1,
                'created_at' => '2026-09-08 05:03:18',
                'updated_at' => '2026-09-08 05:03:18',
            ),
        ));
        
        
    }
}